use alloc::string::String;
use super::super::storage::ata;

#[derive(Clone, Copy, Debug)]
pub struct Superblock {
pub inodes_count: u32,
pub blocks_count: u32,
pub r_blocks_count: u32,
pub free_blocks_count: u32,
pub free_inodes_count: u32,
pub first_data_block: u32,
pub log_block_size: u32,
pub log_frag_size: u32,
pub blocks_per_group: u32,
pub frags_per_group: u32,
pub inodes_per_group: u32,
pub mtime: u32,
pub wtime: u32,
pub mnt_count: u16,
pub max_mnt_count: u16,
pub magic: u16,
pub state: u16,
pub errors: u16,
pub minor_rev_level: u16,
pub lastcheck: u32,
pub checkinterval: u32,
pub creator_os: u32,
pub rev_level: u32,
pub def_resuid: u16,
pub def_resgid: u16,
pub first_ino: u32,
pub inode_size: u16,
pub block_group_nr: u16,
pub feature_compat: u32,
pub feature_incompat: u32,
pub feature_ro_compat: u32,
pub uuid: u128,
pub volume_name: String,
pub last_mounted: [u8; 64],
pub algo_bitmap: u32,
pub prealloc_blocks: u8,
pub prealloc_dir_blocks: u8,
pub alignment_journaling_support: u16,
pub journal_uuid: u128,
pub journal_inum: u32,
pub last_orphan: u32,
pub hash_seed: u128,
pub def_hash_version: u8,
pub default_mount_options: u32,
pub first_meta_bg: u32,
}


